SERVICE:
  name: Название проекта
  secret_key: test_key
  ip_cam: 0
  debug: 1
  debug_temp_path: ./logs/temp/
  dataset_path: ./dataset/ # Папка, куда сохраняется результат работы cropping_controller контроллера
  crop_size_width: 120
  crop_size_height: # Если пусто, будет найдено пропорциональное значение.
  min_time_between_rec: 60 # Минимальное время между записью сотрудника. По умолчанию 60 сек. Ед. изм. в секундах
  person_display_path: ./static_files/images/persons/
  export_path: ./static_files/export/
CROPPING_COMPONENT:
  filling: 40
  cascade: ./config/cv2/lbpcascades/lbpcascade_frontalface.xml
  crop_size_width: 120
  crop_size_height: # Если пусто, будет найдено пропорциональное значение.
RECOGNITION_COMPONENT:
  persons_path: ./persons
  blocked_persons: blocked # Название папки в ./persons, для заблокированных сотрудников
  tolerance: 0.5
DB_CONFIG:
  driver: mysqlite # mysqlite, mysql
  db_path: ../db/
  host: face_control_mysql
  port: 33060
  bind_address: 0.0.0.0
  user: root
  password: root
  dbname: face_control
  charset: utf8mb4
LANGUAGE:
  only_one_face: Идентификация проходит только по очереди
  come_closer: Подойдите ближе
  no_data: Нет данных
  unknown_data_format: Неизвестный формат данных
  recognition_success: Проходите
  unknown_person: Не могу вас определить. Подойдите ближе или дальше.
  confirmed_person: Личность подтверждена.
  access_denied: Доступ запрещен.
  person_path_notfound: Нет папки с сотрудниками.
  response_format_is_not_supported: Этот формат ответа пока не поддерживается
  invalid_date_format: Неверный формат даты
  required_fields_not_filled: Не заполнены обязательные поля
  employee_record_failed: Запись сотрудника не удалась
  employees_notfound: Сотрудники не найдены
  employee_notfound: Сотрудник не найден
  photos_not_attached: Фотографии не прикреплены
  not_all_required_fields_are_filled_in: Заполнены не все обязательные поля
  i_can_identify_the_face_in_the_photo: Не могу определить лицо на фото
  i_can_delete_an_employee: Не могу удалить сотрудника
  employee_removed: Сотрудник удален
  i_can_move_an_employee_to_trash: Не могу переместить сотрудника в корзину
  employee_has_been_moved_to_trash: Сотрудник перемещен в корзину
  i_can_block_an_employee: Не могу заблокировать сотрудника
  employee_is_blocked: Сотрудник заблокирован
  task_has_been_put_to_work: Задача поставлена в работу
  file_format_is_not_supported: Формат файла не поддерживается
  can_generate_statistics: Не могу сформировать статистику
  contact_the_technical_department: Обратитесь в технический отдел
  no_statistics_available: Статистические данные отсутствуют