SERVICE:
  name: Название проекта
  secret_key: test_key
  ip_cam: 0
  debug: 1
  crop_size_width: 120
  crop_size_height: # Если пусто, будет найдено пропорциональное значение.
  min_time_between_rec: 60 # Минимальное время между записью сотрудника. По умолчанию 60 сек. Ед. изм. в секундах
  export_path: ../files/export/
  logs_path: ./logs/
CROPPING_CONFIG:
  filling: 40
  cascade: ./config/cv2/lbpcascades/lbpcascade_frontalface.xml
  crop_size_width: 120
  crop_size_height: # Если пусто, будет найдено пропорциональное значение.
  dataset_path: ../files/dataset/ # Папка, куда сохраняется результат работы cropping
DB_CONFIG:
  db_dir: ../db/
  backup_db_dir: ../db/backup/
  dump_db_path: ./assets/dumps/dump.sql
  dbname: face_control
EMPLOYEES_CONFIG:
  person_display_path: ../files/persons/
RECOGNITION_COMPONENT:
  tolerance: 0.5
LANGUAGE:
  only_one_face: На фото должен присутствовать один сотрудник
  no_data: Нет данных
  no_face: Не получается определить лицо на фото
  enter_employee_full_name: Введите ФИО сотрудника
  enter_employee_position: Введите должность сотрудника
  not_single_photo_has_been_added: Не добавлено ни одного фото
  unknown_data_format: Неизвестный формат данных
  invalid_date_format: Неверный формат даты
  required_fields_not_filled: Не заполнены обязательные поля
  employee_record_failed: Запись сотрудника не удалась
  employee_added: Сотрудник добавлен
  employees_notfound: Сотрудники не найдены
  employee_notfound: Сотрудник не найден
  photos_not_attached: Фотографии не прикреплены
  i_can_identify_the_face_in_the_photo: Не могу определить лицо на фото
  i_can_delete_an_employee: Не могу удалить сотрудника
  employee_removed: Сотрудник удален
  i_can_move_an_employee_to_trash: Не могу переместить сотрудника в корзину
  employee_has_been_moved_to_trash: Сотрудник перемещен в корзину
  i_can_block_an_employee: Не могу заблокировать сотрудника
  employee_is_blocked: Сотрудник заблокирован
  file_format_is_not_supported: Формат файла не поддерживается
  can_generate_statistics: Не могу сформировать статистику
  contact_the_technical_department: Обратитесь в технический отдел
  no_statistics_available: Статистические данные отсутствуют